<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../src/PriceCheck.Windows/Driver/Lu4Device.cs" Link="Lu4Device.cs" />
    <Compile Include="../../src/PriceCheck.Windows/Driver/ClientProcessStatus.cs" Link="ClientProcessStatus.cs" />
    <Compile Include="../../src/PriceCheck.Windows/Driver/ProxyGuardStatus.cs" Link="ProxyGuardStatus.cs" />
  </ItemGroup>
</Project>
