"""Reversible plaintext observation, independent of the Collector's radar ring.

Both hooks copy bytes and then execute the prior path unchanged. No packets,
target actions, movement or shop operations are generated by this module.
"""
from __future__ import annotations

import argparse
import json
import re
import struct
import time
from datetime import datetime, timezone

from lab import (Code, Lu4MemoryClient, absolute_jump, directory, guard, load,
                 patch_region, position, read_exact, save, write_exact)
from resolve_lu4_direct_hook import executable_sections

RX_SIGNATURE = bytes.fromhex("44 0F B6 C2 41 88 4A FF 44 3B CE 7C")
RX_ORIGINAL = bytes.fromhex("41 0F B6 1E B8 01 00 00 00 80 FB FE 41 BF 03 00 00 00")
TX_ORIGINAL = bytes.fromhex("41 8B 00 45 32 D2 45 33 C9 4C 8B D9 85 C0")
MAX_PACKET = 0x4000
SLOT_SIZE = MAX_PACKET + 32
CAPACITY = 64
PUSH = bytes.fromhex("9C 50 51 52 41 50 41 51 41 52 41 53 56 57")
POP = bytes.fromhex("5F 5E 41 5B 41 5A 41 59 41 58 5A 59 58 9D")


def build_stub(kind: str, control: int, records: int, original: bytes, continuation: int) -> bytes:
    c = Code()
    c.emit(PUSH)
    setup = {"rx": "8B CE 4C 89 F6", "tx": "48 89 D6 41 8B 08",
             "winsock": "48 89 D6 44 89 C1"}
    c.emit(bytes.fromhex(setup[kind]))
    c.emit(bytes.fromhex("85 C9"))
    c.branch32(bytes.fromhex("0F 8E"), "restore")
    c.emit(bytes.fromhex("81 F9 00 00 10 00"))
    c.branch32(bytes.fromhex("0F 87"), "restore")
    c.emit(b"\x49\xBB" + struct.pack("<Q", control))
    c.emit(bytes.fromhex("BA 01 00 00 00 41 87 13 85 D2"))
    c.branch32(bytes.fromhex("0F 85"), "busy")
    c.emit(bytes.fromhex("49 8B 43 08 48 FF C0 49 89 C1 41 83 E1 3F"))
    c.emit(b"\x48\xBF" + struct.pack("<Q", records))
    c.emit(bytes.fromhex("4A 8B 3C CF 49 89 FA"))  # pointer table; r10 holds the slot
    c.emit(bytes.fromhex("48 C7 07 00 00 00 00 89 4F 08 48 89 77 10"))
    c.emit(bytes.fromhex("48 8B 54 24 50 48 89 57 18"))
    c.emit(b"\x81\xF9" + struct.pack("<I", MAX_PACKET))
    c.branch32(bytes.fromhex("0F 86"), "copy")
    c.emit(b"\xB9" + struct.pack("<I", MAX_PACKET))
    c.label("copy")
    c.emit(bytes.fromhex("89 4F 0C 48 83 C7 20 FC F3 A4"))
    c.emit(bytes.fromhex("49 89 02 49 89 43 08 41 C7 03 00 00 00 00"))
    c.branch32(b"\xE9", "restore")
    c.label("busy")
    c.emit(bytes.fromhex("F0 49 FF 43 10"))
    c.label("restore")
    c.emit(POP)
    c.emit(original)
    c.emit(absolute_jump(continuation, 14))
    return c.finish()


def discover(client: Lu4MemoryClient, pid: int, base: int) -> int:
    cached = directory(pid) / "packet-sites.json"
    if cached.exists():
        data = load(pid, cached.name)
        address = base + data["receive_rva"]
        if read_exact(client, pid, address - 17, len(RX_SIGNATURE)) == RX_SIGNATURE:
            return address
    matches = set()
    pattern = re.compile(re.escape(RX_SIGNATURE) + b"." + re.escape(bytes.fromhex("48 01 75 50")), re.DOTALL)
    for section in executable_sections(read_exact(client, pid, base, 0x1000)):
        carry = b""
        for offset in range(0, int(section["size"]), 0x100000):
            start = base + int(section["rva"]) + offset
            raw = read_exact(client, pid, start, min(0x100000, int(section["size"]) - offset))
            data = carry + raw
            for match in pattern.finditer(data):
                matches.add(start - len(carry) + match.start() + 17)
            carry = data[-32:]
    if len(matches) != 1:
        raise RuntimeError(f"expected unique receive hook site: {matches}")
    address = matches.pop()
    save(pid, "packet-sites.json", {"pid": pid, "image_base": base, "receive_rva": address - base,
                                    "encrypt_rva": 0x4C009A0})
    return address


def install(pid: int) -> None:
    state_path = directory(pid) / "packet-capture-state.json"
    if state_path.exists():
        raise RuntimeError("capture state already exists; inspect/restore before installing")
    state = {"pid": pid, "hooks": [], "created_at": datetime.now(timezone.utc).isoformat()}
    with Lu4MemoryClient() as client:
        base = guard(client, pid)
        state["image_base"] = base
        rx = discover(client, pid, base)
        for kind, address, expected in (("rx", rx, RX_ORIGINAL), ("tx", base + 0x4C009A0, TX_ORIGINAL)):
            original = read_exact(client, pid, address, len(expected))
            if original != expected:
                # Permit only the known radar patch and validate its three ring pointers.
                if kind != "rx" or original[:6] != bytes.fromhex("FF 25 00 00 00 00"):
                    raise RuntimeError(f"unexpected {kind} prologue: {original.hex()}")
                stub = struct.unpack_from("<Q", original, 6)[0]
                raw = read_exact(client, pid, stub, 0x81)
                ring = struct.unpack_from("<Q", raw, 0x29)[0]
                if not ring or struct.unpack_from("<Q", raw, 0x43)[0] != ring + 4 or struct.unpack_from("<Q", raw, 0x79)[0] != ring:
                    raise RuntimeError("unknown receive hook; refusing to chain")
            cave, _ = client.allocate_process_memory(pid, 0x1000)
            records = []
            try:
                for _ in range(CAPACITY):
                    record, _ = client.allocate_process_memory(pid, SLOT_SIZE)
                    records.append(record)
            except Exception:
                for record in records:
                    client.free_process_memory(pid, record)
                client.free_process_memory(pid, cave)
                raise
            control = cave + 0x800
            record_table = cave + 0x900
            code = build_stub(kind, control, record_table, original, address + len(original))
            patch = absolute_jump(cave, len(original))
            hook = {"kind": kind, "address": address, "original": original.hex(), "patch": patch.hex(),
                    "cave": cave, "control": control, "records": records, "stub_hex": code.hex()}
            # Write rollback metadata before touching the live entry point.
            state["hooks"].append(hook)
            save(pid, state_path.name, state)
            write_exact(client, pid, cave, code)
            write_exact(client, pid, control, bytes(32))
            write_exact(client, pid, record_table, struct.pack(f"<{CAPACITY}Q", *records))
            patch_region(client, pid, address, patch)
    print(json.dumps({"state": str(state_path), "hooks": [h["kind"] for h in state["hooks"]]}))


def restore(pid: int) -> None:
    state = load(pid, "packet-capture-state.json")
    with Lu4MemoryClient() as client:
        if guard(client, pid) != state["image_base"]:
            raise RuntimeError("PID/base changed; refusing stale rollback")
        for hook in reversed(state["hooks"]):
            current = read_exact(client, pid, hook["address"], len(bytes.fromhex(hook["patch"])))
            if current not in (bytes.fromhex(hook["patch"]), bytes.fromhex(hook["original"])):
                raise RuntimeError("live patch changed; cannot restore")
            patch_region(client, pid, hook["address"], bytes.fromhex(hook["original"]))
            if read_exact(client, pid, hook["address"], len(current)) != bytes.fromhex(hook["original"]):
                raise RuntimeError("restore verification failed")
    # A thread may still be in the old cave: leave the small allocations until exit.
    save(pid, "packet-capture-restored.json", {**state, "restored_at": datetime.now(timezone.utc).isoformat(),
                                              "allocations_retained_until_process_exit": True})
    (directory(pid) / "packet-capture-state.json").unlink()
    print("Both packet hooks restored and verified; allocations retained until client exit.")


def snapshot(client: Lu4MemoryClient, pid: int, hook: dict, after: int) -> tuple[list[dict], int, int]:
    if read_exact(client, pid, hook["address"], len(bytes.fromhex(hook["patch"]))) != bytes.fromhex(hook["patch"]):
        raise RuntimeError(f"{hook['kind']} hook no longer installed")
    busy, sequence, dropped = struct.unpack("<I4xQQ", read_exact(client, pid, hook["control"], 24))
    if busy:
        return [], after, dropped
    if sequence - after > CAPACITY:
        raise RuntimeError(f"{hook['kind']} capture overrun: {sequence-after} > {CAPACITY}")
    rows = []
    for seq in range(after + 1, sequence + 1):
        address = hook["records"][seq % CAPACITY]
        header = read_exact(client, pid, address, 32)
        observed, length, copied, source, caller = struct.unpack("<QIIQQ", header)
        if observed != seq or copied > MAX_PACKET:
            raise RuntimeError("record overwritten or incomplete")
        raw = read_exact(client, pid, address + 32, copied)
        if read_exact(client, pid, address, 8) != header[:8]:
            raise RuntimeError("record changed while reading")
        rows.append({"direction": hook["kind"], "sequence": seq, "length": length, "copied": copied,
                     "source": hex(source), "caller": hex(caller), "hex": raw.hex(),
                     "observed_at": datetime.now(timezone.utc).isoformat()})
    return rows, sequence, dropped


def monitor(pid: int, seconds: float, name: str) -> None:
    state = load(pid, "packet-capture-state.json")
    result = {"pid": pid, "packets": [], "samples": [], "dropped": {}}
    output = directory(pid) / f"{name}.jsonl"
    with Lu4MemoryClient() as client, output.open("w", encoding="utf-8") as stream:
        if guard(client, pid) != state["image_base"]:
            raise RuntimeError("PID/image mismatch")
        after = {h["kind"]: struct.unpack("<Q", read_exact(client, pid, h["control"] + 8, 8))[0] for h in state["hooks"]}
        result["start_sequences"] = dict(after)
        started = time.monotonic()
        next_sample = 0.0
        while time.monotonic() - started < seconds:
            for hook in state["hooks"]:
                rows, after[hook["kind"]], dropped = snapshot(client, pid, hook, after[hook["kind"]])
                result["dropped"][hook["kind"]] = dropped
                for row in rows:
                    stream.write(json.dumps(row) + "\n")
                stream.flush()
                result["packets"].extend(rows)
            if time.monotonic() - started >= next_sample:
                result["samples"].append({"elapsed": time.monotonic() - started, **position(client, pid)})
                next_sample += 0.2
            time.sleep(0.005)
        result["end_sequences"] = after
    save(pid, f"{name}.json", result)
    print(json.dumps({"path": str(directory(pid) / f"{name}.json"), "packets": len(result["packets"]),
                      "dropped": result["dropped"]}))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("pid", type=int)
    parser.add_argument("command", choices=("install", "restore", "monitor"))
    parser.add_argument("--seconds", type=float, default=15)
    parser.add_argument("--name", default="observation")
    args = parser.parse_args()
    if args.command == "install":
        install(args.pid)
    elif args.command == "restore":
        restore(args.pid)
    else:
        monitor(args.pid, args.seconds, args.name)
