using PriceCheck.Collector.Models;
using PriceCheck.Collector.Services;

var now=DateTimeOffset.UtcNow;
var folder=Path.Combine(Path.GetTempPath(),"PriceCheck-cycle-tests",Guid.NewGuid().ToString("N"));
var profile=new CollectorProfile();
var queue=new CycleQueue(profile,()=>now,folder);
var checks=0;
void Check(bool value,string message) { if(!value) throw new Exception(message); checks++; }
BrokerInventoryRow Row(int item=1,long amount=10,string name=" Shop ",int oid=7)=>new(){TraderName=name,TraderObjectId=oid,StoreType=1,ItemId=item,Amount=amount};
void Broker(bool complete,params BrokerInventoryRow[] rows)=>queue.ApplyBroker(new(){CapturedAtUtc=now,Rows=rows},complete,now);
RadarSnapshot Radar(double x=100,int oid=7)=>new(){Traders=[new(oid,"SHOP",1,x,200,0,true,now),new(9,"RADAR ONLY",1,300,300,0,true,now)]};
queue.Observe(Radar());
Check(queue.Status(new()).Active==0,"Radar must not discover traders");
Broker(true,Row());queue.Observe(Radar());
Check(queue.Status(new()).Active==1 && queue.Ready(0,0).Count==1,"Broker admits known identity");
var target=queue.Ready(0,0).Single();queue.Complete(target,now);
Check(queue.Ready(0,0).Count==0,"Successful check clears queue");
now=now.AddMinutes(1);Broker(true,Row(amount:3));
Check(queue.Ready(0,0).Count==0,"Quantity-only change must not enqueue");
queue=new(profile,()=>now,folder);queue.Observe(new());queue.Observe(Radar(oid:99));
Check(queue.Ready(0,0).Count==0,"Reload and cold radar must not mistake PID rebinding for reopened shop");
now=now.AddHours(24);
Check(queue.Ready(0,0).Single().Reason=="24-hour check","24-hour deadline");
target=queue.Ready(0,0).Single();queue.Fail(target,"Blocked");
Check(queue.Ready(0,0).Count==0 && queue.Status(new()).Deferred==1,"Backoff after stall");
now=now.AddMinutes(2);Check(queue.Ready(0,0).Count==1,"Deferred shop returns after cooldown");
queue.Complete(target,now);now=now.AddSeconds(1);Broker(true,Row(oid:99),Row(item:2,oid:99));
Check(queue.Ready(0,0).Count==1,"New item requires price");
target=queue.Ready(0,0).Single();queue.Observe(Radar(x:140,oid:99));queue.Complete(target,now);
Check(queue.Ready(0,0).Count==1,"Stale capture must not clear moved shop revision");
queue.Complete(queue.Ready(0,0).Single(),now);now=now.AddSeconds(1);Broker(false);
Check(queue.Status(new()).Active==1,"Partial pass cannot remove absence");
Broker(true);Check(queue.Status(new()).Active==0,"Complete pass removes absence");
queue.Observe(Radar(x:140,oid:99));Check(queue.Status(new()).Active==0,"Radar cannot reactivate removed trader");
now=now.AddSeconds(1);Broker(true,Row(oid:99));Check(queue.Ready(0,0).Count==1,"Broker return enqueues price");
queue.Complete(queue.Ready(0,0).Single(),now);now=now.AddSeconds(1);Broker(true,Row(oid:99),Row(oid:99));
Check(queue.Ready(0,0).Count==1,"New multiplicity requires price");
var isolated=new CycleQueue(new CollectorProfile(),()=>now,folder);Check(isolated.Status(new()).Active==0,"Profiles are isolated");
checks += PersistenceChecks.Run();
Console.WriteLine($"MARKET_CYCLE_OK {checks} checks; fixtures: {folder}");
