#pragma once

#ifdef _KERNEL_MODE
#include <ntddk.h>
#else
#include <Windows.h>
#include <winioctl.h>
#endif

#define LU4_PROTOCOL_VERSION 3u
#define LU4_DEVICE_TYPE 0x8337u
#define LU4_MAX_TRANSFER (1024u * 1024u)

#define IOCTL_LU4_GET_PROCESS_BASE \
    CTL_CODE(LU4_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_LU4_READ_PROCESS_MEMORY \
    CTL_CODE(LU4_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_LU4_WRITE_PROCESS_MEMORY \
    CTL_CODE(LU4_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_SUBMIT_TARGET \
    CTL_CODE(LU4_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_CLAIM_TARGET \
    CTL_CODE(LU4_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_LU4_COMPLETE_TARGET \
    CTL_CODE(LU4_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_QUERY_TARGET \
    CTL_CODE(LU4_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_LU4_QUERY_ACTIVE64 \
    CTL_CODE(LU4_DEVICE_TYPE, 0x807, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_LU4_READ_ACTIVE64 \
    CTL_CODE(LU4_DEVICE_TYPE, 0x808, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_LU4_ENCRYPT_PACKET \
    CTL_CODE(LU4_DEVICE_TYPE, 0x809, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_ALLOCATE_PROCESS_MEMORY \
    CTL_CODE(LU4_DEVICE_TYPE, 0x80A, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_PROTECT_PROCESS_MEMORY \
    CTL_CODE(LU4_DEVICE_TYPE, 0x80B, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_FREE_PROCESS_MEMORY \
    CTL_CODE(LU4_DEVICE_TYPE, 0x80C, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_SET_PROXY_REDIRECT \
    CTL_CODE(LU4_DEVICE_TYPE, 0x80D, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_QUERY_PROXY_GUARD \
    CTL_CODE(LU4_DEVICE_TYPE, 0x810, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_LU4_QUERY_PROCESS_STATUS \
    CTL_CODE(LU4_DEVICE_TYPE, 0x811, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_LU4_PROBE_CAS_ACTIVE64_MAC \
    CTL_CODE(LU4_DEVICE_TYPE, 0x80E, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_LU4_PROBE_CAS_ACTIVE64_EIGHT \
    CTL_CODE(LU4_DEVICE_TYPE, 0x80F, METHOD_BUFFERED, FILE_WRITE_DATA)

#define LU4_ROLLING_KEY_SIZE 17u
#define LU4_RC4_SBOX_SIZE 256u
#define LU4_RC4_STATE_SIZE 0x108u
#define LU4_TARGET_STATE_INDEX 1u
#define LU4_MAX_PACKET_SIZE 0x1000u

#define LU4_TARGET_STATE_EMPTY 0u
#define LU4_TARGET_STATE_PENDING 1u
#define LU4_TARGET_STATE_CLAIMED 2u
#define LU4_TARGET_STATE_COMPLETED 3u

#define LU4_TARGET_RESULT_NONE 0u
#define LU4_TARGET_RESULT_OK 1u
#define LU4_TARGET_RESULT_REJECTED 2u
#define LU4_TARGET_RESULT_EXCEPTION 3u

typedef struct _LU4_BASE_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONGLONG BaseAddress;
} LU4_BASE_REQUEST, *PLU4_BASE_REQUEST;

typedef struct _LU4_COPY_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONGLONG Address;
    ULONG Size;
    ULONG BytesTransferred;
    UCHAR Data[1];
} LU4_COPY_REQUEST, *PLU4_COPY_REQUEST;

#define LU4_COPY_HEADER_SIZE FIELD_OFFSET(LU4_COPY_REQUEST, Data)

typedef struct _LU4_TARGET_COMMAND {
    ULONG Version;
    ULONG ProcessId;
    ULONGLONG Sequence;
    LONG ObjectId;
    LONG X;
    LONG Y;
    LONG Z;
    ULONG Flags;
    ULONG State;
    ULONG Result;
    ULONG Reserved;
} LU4_TARGET_COMMAND, *PLU4_TARGET_COMMAND;

typedef struct _LU4_KERNEL_MODULE_INFO {
    ULONG Version;
    ULONG Reserved;
    ULONGLONG BaseAddress;
    ULONG ImageSize;
    ULONG Reserved2;
} LU4_KERNEL_MODULE_INFO, *PLU4_KERNEL_MODULE_INFO;

typedef struct _LU4_MODULE_READ_REQUEST {
    ULONG Version;
    ULONG Reserved;
    ULONGLONG Offset;
    ULONG Size;
    ULONG BytesTransferred;
    UCHAR Data[1];
} LU4_MODULE_READ_REQUEST, *PLU4_MODULE_READ_REQUEST;

/* Implemented only by the separately loaded LU4_PROBE_BUILD test driver. */
typedef struct _LU4_PROBE_ACTIVE64_MAC_REQUEST {
    ULONG Version;
    ULONG Offset;
    UCHAR Expected[6];
    UCHAR Replacement[6];
    ULONG BytesWritten;
} LU4_PROBE_ACTIVE64_MAC_REQUEST, *PLU4_PROBE_ACTIVE64_MAC_REQUEST;

/* Implemented only by the separately loaded LU4_PROBE_BUILD test driver. */
typedef struct _LU4_PROBE_ACTIVE64_EIGHT_REQUEST {
    ULONG Version;
    ULONG Offset;
    UCHAR Expected[8];
    UCHAR Replacement[8];
    ULONG BytesWritten;
} LU4_PROBE_ACTIVE64_EIGHT_REQUEST, *PLU4_PROBE_ACTIVE64_EIGHT_REQUEST;

#define LU4_MODULE_READ_HEADER_SIZE FIELD_OFFSET(LU4_MODULE_READ_REQUEST, Data)

typedef struct _LU4_PACKET_CRYPTO_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONGLONG BufferAddress;
    ULONG Size;
    ULONG StateIndex;
    ULONGLONG RollingKeyAddress;
    ULONGLONG StateOffset;
    LONG CounterBias;
    ULONG BytesTransferred;
} LU4_PACKET_CRYPTO_REQUEST, *PLU4_PACKET_CRYPTO_REQUEST;

typedef struct _LU4_RC4_STATE {
    ULONG I;
    ULONG J;
    UCHAR Sbox[LU4_RC4_SBOX_SIZE];
} LU4_RC4_STATE, *PLU4_RC4_STATE;

typedef struct _LU4_VIRTUAL_MEMORY_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONGLONG Address;
    ULONGLONG Size;
    ULONG Protection;
    ULONG OldProtection;
    ULONGLONG Reserved;
} LU4_VIRTUAL_MEMORY_REQUEST, *PLU4_VIRTUAL_MEMORY_REQUEST;

typedef struct _LU4_PROXY_REDIRECT_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONG HostProcessId;
    ULONG ListenerPort;
    ULONG Enable;
    LONG Status;
    ULONG Stage;
} LU4_PROXY_REDIRECT_REQUEST, *PLU4_PROXY_REDIRECT_REQUEST;

#define LU4_PROXY_REDIRECT_MAGIC 0x5052344Cu
/* Guard schema 1: IPv4 TCP redirect, deny other egress, inherit, retain on host exit. */
#define LU4_PROXY_GUARD_CAPABILITIES 31u
typedef struct _LU4_PROXY_GUARD_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONG HostProcessId;
    ULONG ListenerPort;
    ULONG Capabilities;
    ULONG Active;
    ULONGLONG BlockedConnections;
} LU4_PROXY_GUARD_REQUEST, *PLU4_PROXY_GUARD_REQUEST;

/* Optional output extension; the 32-byte request and base response stay valid. */
typedef struct _LU4_PROXY_GUARD_DETAILS {
    LU4_PROXY_GUARD_REQUEST Base;
    ULONG BlockedProtocol;
    ULONG BlockedLayer;
    ULONG BlockedAddress;
    ULONG BlockedPort;
} LU4_PROXY_GUARD_DETAILS, *PLU4_PROXY_GUARD_DETAILS;

typedef struct _LU4_PROCESS_STATUS_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONGLONG CreationTime;
    ULONG Active;
    LONG ExitStatus;
} LU4_PROCESS_STATUS_REQUEST, *PLU4_PROCESS_STATUS_REQUEST;

typedef struct _LU4_PROXY_REDIRECT_CONTEXT {
    ULONG Magic;
    ULONG ProcessId;
    ULONG AddressNetworkOrder;
    USHORT PortNetworkOrder;
    USHORT Reserved;
} LU4_PROXY_REDIRECT_CONTEXT, *PLU4_PROXY_REDIRECT_CONTEXT;

/* Additive per-process registry identity. Never writes Windows registry values. */
#define IOCTL_LU4_SET_PROCESS_IDENTITY \
    CTL_CODE(LU4_DEVICE_TYPE, 0x812, METHOD_BUFFERED, FILE_WRITE_DATA)
#define LU4_PROCESS_IDENTITY_CAPABILITIES 15u /* GUIDs, EDID, additional registry identity */

/* Resident working-set policy; never caps committed memory or frees allocations. */
#define IOCTL_LU4_SET_WORKING_SET \
    CTL_CODE(LU4_DEVICE_TYPE, 0x813, METHOD_BUFFERED, FILE_WRITE_DATA)
#define LU4_WORKING_SET_APPLY 1u
#define LU4_WORKING_SET_RESTORE 2u
typedef struct _LU4_WORKING_SET_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONGLONG CreationTime;
    ULONGLONG MinimumBytes;
    ULONGLONG MaximumBytes;
    ULONG Flags;
    ULONG Operation;
    LONG Status;
    ULONG Reserved;
} LU4_WORKING_SET_REQUEST, *PLU4_WORKING_SET_REQUEST;
typedef struct _LU4_PROCESS_IDENTITY_REQUEST {
    ULONG Version;
    ULONG ProcessId;
    ULONGLONG CreatedTime;
    GUID ProfileId;
    WCHAR MachineGuid[40];
    WCHAR HardwareProfileGuid[40];
    WCHAR SystemUuid[40];
    ULONG Capabilities;
    ULONG Reserved;
    WCHAR ProductId[64];
    WCHAR SusClientId[40];
    WCHAR SqmMachineId[40];
    WCHAR VideoIdentifier[40];
    WCHAR ComputerName[64];
    WCHAR ProcessorModel[128];
    UCHAR ProcessorRevision[8];
    ULONG InstallDate;
    ULONG Reserved2;
} LU4_PROCESS_IDENTITY_REQUEST, *PLU4_PROCESS_IDENTITY_REQUEST;
